name: Code Quality

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install tools
        run: |
          brew install swiftlint swift-format

      - name: SwiftLint
        run: swiftlint lint Sources

      - name: Swift Format
        run: swift-format lint --recursive Sources --strict
